// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkh_OMzDBSNEy3idrIMRV0V1gV_7RePGE',
    appId: '1:1075482216613:web:8e6c8e3901c572aaaea54c',
    messagingSenderId: '1075482216613',
    projectId: 'panchshala-hotel',
    authDomain: 'panchshala-hotel.firebaseapp.com',
    storageBucket: 'panchshala-hotel.appspot.com',
    measurementId: 'G-40PLW1SKP5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDU_HnVTwY1jWN1Hfuwo4ydCihI0RfxM_I',
    appId: '1:1075482216613:android:7097c3f90e31b3faaea54c',
    messagingSenderId: '1075482216613',
    projectId: 'panchshala-hotel',
    storageBucket: 'panchshala-hotel.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtvubhwcWUbkvWHhq5FGmjVqxW7N3-GCk',
    appId: '1:1075482216613:ios:5f2fc7a0efecd280aea54c',
    messagingSenderId: '1075482216613',
    projectId: 'panchshala-hotel',
    storageBucket: 'panchshala-hotel.appspot.com',
    iosClientId:
        '1075482216613-khkjlltvs017u002lk2b0k41lb99dvj9.apps.googleusercontent.com',
    iosBundleId: 'com.panchshala.panchshala',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtvubhwcWUbkvWHhq5FGmjVqxW7N3-GCk',
    appId: '1:1075482216613:ios:5f2fc7a0efecd280aea54c',
    messagingSenderId: '1075482216613',
    projectId: 'panchshala-hotel',
    storageBucket: 'panchshala-hotel.appspot.com',
    iosClientId:
        '1075482216613-khkjlltvs017u002lk2b0k41lb99dvj9.apps.googleusercontent.com',
    iosBundleId: 'com.panchshala.panchshala',
  );
}




// import 'package:firebase_core/firebase_core.dart';
// import 'firebase_options.dart';

// // ...

// await Firebase.initializeApp(
//     options: DefaultFirebaseOptions.currentPlatform,
// );